### ISSUE TITLE
this example works for Windows too?

### ISSUE THREAD

**Issue by matiastucci** [iffy/electron-updater-example#11]

**Comment by iffy** [comment]
I've heard it does but I don't have Windows to test it. Issue #6 is probably the only incompatibly.

**Comment by matiastucci** [comment]
ok, thanks, I'll try. One more question, how the app knows where to check if there is a new update? if you never do `autoUpdater.setFeedURL(url)`

**Comment by iffy** [comment]
It uses "magic" (i.e. I don't know exactly).  I wish it was less magical.  But look at item 2 on the README: https://github.com/iffy/electron-updater-example

Reopen if you have other questions.
