### ISSUE TITLE
there is any way that i can make manualy updates not auto

### ISSUE THREAD

**Issue by George35mk** [iffy/electron-updater-example#12]
when the update is avalible is starting downloading from my git hub ucount and when the update is finish is close the app and install the updates i dont want that , i want the user to see on status if update is avalible and if is want the update in gona download the update and a popup window is gona say you want the update to install now ?? 

how  i gona make this??

i dont want the app to close automaticle but only if the user want now or on restar or on the other sessison

**Comment by iffy** [comment]
@George35mk Yes, you can have it actually install whenever you want, though I'm not sure how to have it install on the next start.

This part of the code is what you would change: https://github.com/iffy/electron-updater-example/blob/master/main.js#L125

```javascript
autoUpdater.on('update-downloaded', (ev, info) => {
  // Wait 5 seconds, then quit and install
  // In your application, you don't need to wait 5 seconds.
  // You could call autoUpdater.quitAndInstall(); immediately
  setTimeout(function() {
    autoUpdater.quitAndInstall();  
  }, 5000)
})
```

Instead of doing `setTimeout` you could create a new window or dialog that asks the user if they want to update.  Make some code that calls `autoUpdater.quitAndInstall()` when you'd like it to happen.

Please reopen if you have more questions.

**Comment by George35mk** [comment]
thnx iffy i gona try to make new window 1 more question brother

why i canot have all the code about update not on main process but in seperate file like updater.js 

can i do this think or how i can notified about updates after the user log in the app after 10min 

can i do that??

**Comment by iffy** [comment]
@George35mk 

Yes, you can put all your updater code in another file and then import/require it into `main.js`.

If you wanted to check for updates after 10 minutes, you'd call `checkForUpdates` like this (instead of inside the `app.on('ready', function() { ... })`):

```javascript
setTimeout(function() {
  autoUpdater.checkForUpdates();
}, 10 * 60000);
```

If you wanted to check **every** 10 minutes change `setTimeout` to `setInterval`.

**Comment by George35mk** [comment]
iffy if they are select not to update now for example and they are close the application if they open the app on next time how the new update in gona start to execute setup-my app.exe ??  or the update is gona start without problem

**Comment by iffy** [comment]
@George35mk If they choose not to update and close the app, *I think* it will start over (re-download the update and prompt them again).  At least I think that's how it works on this version of `electron-updater`.  But maybe a newer version will keep downloads between app restarts?  I'd ask that in the Slack channel: https://electron-builder.slack.com

**Comment by George35mk** [comment]
if they select no to update and the update has complete that new file (myNewUpdate-setup-v1.078) iffy can you tell me were this new setup.exe is stored and if i can run this comand after the app is relanch 
`autoUpdater.quitAndInstall()`

**Comment by George35mk** [comment]
the problem with autoUpdate is when the user working with my app suddenly the app is close and start the update

**Comment by George35mk** [comment]
iffy i found that the update exe file is stored on 

C:\Users\iffy\AppData\Local\Temp\up-BL4tQA\yourApp-setup-v2.0.7.exe

ok if the user dont wan the app to installed ,but the app have downloaded  on that dir can instaled when the user try to lanch the app in the second 

can you make a npm package with the name manual downloader for electron apps 👍  is easy for you i never make module or npm package i dont know

**Comment by iffy** [comment]
@George35mk I've never made an npm package either :)  I just made this demo repository because it took me so long to figure out how to get AutoUpdater working.

@develar If an update has been downloaded, then the app is restarted, is there a way for the app to not have to download the update again and to know that it's already been downloaded?

**Comment by George35mk** [comment]
if you see the app path were is stored you find the parend pathe is random if know what algorith create that path i think you gona find how to chec if update exis and not to redownloaded again

C:\Users\iffy\AppData\Local\Temp\**up-BL4tQA**\yourApp-setup-v2.0.7.exe

**Comment by George35mk** [comment]
iffy i think you can make it i beilive to you 4 days i try to make updater 4 DAYS and finaly i come tou your github example page thank god i make it put now i face this problem

**Comment by iffy** [comment]
@George35mk let's see if develar already has a solution for you.

**Comment by George35mk** [comment]
iffy are you there???

**Comment by George35mk** [comment]
i think i have find the solution but i need to help me because i am not soo expert 

i fount that in my main.js console i see all that messages from the console

```
Wait for app ready
[23:16:15:0673] [info] App starting...
init: 183.001ms
1.6.2
[23:16:15:0857] [info] Checking for update
[23:16:15:0864] [info] Checking for update...
[23:16:19:0281] [info] Found version 2.0.5 (url: 
[23:16:19:0282] [info] Update available.
[23:16:19:0285] [info] Downloading update from 
[23:16:20:0775] [info] Download progress...
[23:16:22:0207] [info] Download progress...
[23:16:23:0208] [info] Download progress...
```

if i can comunicate with **ipcMain** 

i make this function

````
function sendThatUpdateExist () {
  // body
  ipcMain.on('async', (event, arg) => {  
    // Reply on async message from renderer process
    event.sender.send('ifUpdateExist', 1);
  });
}



autoUpdater.on('checking-for-update', () => {
  sendStatusToWindow('Checking for update...');

  sendThatUpdateExist ();
})
````

**Comment by George35mk** [comment]
in my render process i can take that data and i think with simple alert(); i can now if somethink is hapend inside that main.js

**Comment by George35mk** [comment]
with that way i can check if there is update i can sent **1** if yes and **0** if no 
and i can take that msg from main what you say ???

**Comment by develar** [comment]
1. In my app auto-update doesn't close app if update exists, only notification send (https://github.com/develar/onshape-desktop-shell/blob/master/src/AppUpdater.ts#L22).
2. Update installed on quit.

No way to reuse previously downloaded update after restart. I don't think that it is required. Just call `autoUpdater.checkForUpdates` again to download actual update file.

**Comment by George35mk** [comment]
thnx develar

**Comment by George35mk** [comment]
develar i try to install your app but when select to signUp nothink hapent ???

**Comment by George35mk** [comment]
3 times i try to sighUp from the login menu but nothink why??

**Comment by develar** [comment]
@George35mk Sign up using https://www.onshape.com
