### ISSUE TITLE
How to config electron-updater

### ISSUE THREAD

**Issue by mbtakanov** [iffy/electron-updater-example#14]
Hello, I can't understand from the given examples how to configure the updater. I have private company git repo on a company website and the example is all about GitHub. Where do I have to add the url to the repo? Do I have to add a credentials? If yes - where? What is the thing with the access token? I can't understand anything. Can you explain points 4, 5(what do you mean by "Publish with the publish.sh script"?) and 6 without involving GitHub?

**Comment by mbtakanov** [comment]
Thank you for the answer, it really helped. Two more things though.
1. How should the repo look like? I mean what it should contain? Only an .exe (installer) file and latest.yml? Or the source files (before compiling)? Or the files in win-unpacked folder (the compiled files)?
2. Is it possible to make a video in youtube how this work? With all the configs and ect. It would be very helpful.

**Comment by iffy** [comment]
I'm not sure.  @develar, how should files be laid out on the fileserver for a `generic` provider?

**Comment by develar** [comment]
Url — it is base URL for installer and channel update info files. I.e both exe and latest.yml must uploaded. Layout — nothing specific. E.g https://example.com/foo — dir foo must contains these files.

**Comment by iffy** [comment]
So:

```
"url": "https://www.example.com/foo"
```

with these files on the webserver:

```
https://www.example.com/foo/latest.yml
https://www.example.com/foo/myapp Setup.exe
```

Does that work, @mbtakanov ?

**Comment by mbtakanov** [comment]
Ok, I did what you said. I uploaded the `.exe` and `latest.yml` in a `foo` folder in the repo. Then I navigated to the folder and copy the URL. Then I set the URL at the `package.json` in the publish option like this:

```
"publish": [
      {
        "provider": "generic",
        "url": "https://git.companyname.com/repo_name/src/master/foo/"
      }
]
```


Unfortunately, when I start the app, an error pops up:
```
Error: Error: Cannot find channel "latest.yml" update info: HttpError: 404 Not Found
"method: undefined url: https://git.companyname.com/repo_name/src/master/foo/latest.yml\n\n    Please double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n   "
``` 

Could you tell me what's wrong? There is nothing in google when I search the error.

And just out of curiosity, in `latest.yml` there is `sha2: foobarfoobarfoobar...` row. Is there something I must do with it?

**Comment by iffy** [comment]
@mbtakanov If you use your browser to go to the url mentioned in the error do you get a 404 or does it download the file?

@develar is the problem that `method` is `undefined`?

**Comment by iffy** [comment]
@mbtakanov Does this work for you? https://gist.github.com/iffy/0ff845e8e3f59dbe7eaf2bf24443f104

It worked for my updating my macOS app.

**Comment by mbtakanov** [comment]
Hi, thank you for going through this with me. 
1. If I navigate to `https://git.companyname.com/repo_name/src/master/foo/latest.yml` in my browser, it just shows the content of the file just like any other file opened in a repo (example - https://github.com/electron/electron/blob/master/script/bootstrap.py)

2. The instructions in the link you provided - https://gist.github.com/iffy/0ff845e8e3f59dbe7eaf2bf24443f104 helped me to create a working update process (I had to `npm install http-server -g` and use it, no big deal). The question now is, how I can create the same thing, but with a URL of a repo (like the one above) and not with a htpp-server?

**Comment by iffy** [comment]
@mbtakanov 

1. The `generic` provider is for plain old HTTP servers that serve plain old files.  For instance, instead of https://github.com/electron/electron/blob/master/script/bootstrap.py electron-updater is expecting the "Raw" version of that file (i.e. https://raw.githubusercontent.com/electron/electron/master/script/bootstrap.py -- notice that this is from `raw.githubusercontent.com`)

What software are you using to host your git repos on the web?  GitHub? BitBucket? GitLab?  Something else?  I imagine most of them have a way to serve raw files.  More information would help me help you.

2. (You probably don't need the `-g` to install `http-server`)

3. I'm not sure what you mean.  When I update this app, it installs itself and restarts without me having to uninstall then install.

**Comment by mbtakanov** [comment]
My company repo is based on GitHub, everything is the same as github.com, but it's on a private domain. Imagine I'm at the folder where are the `.exe` and `latest.yml`. So, how can I extract a link which will work in the `generic` provider? Is it even possible? I can get the link with the raw `latest.yml` file, but as we know, we need a link which contain both, the `.exe` and `latest.yml` files. My goal here is to make it work with a github like repository and if possible - avoid Amazon S3.
I have `"oneClick": false,` so on update, the app uninstall by itself,  but I have to manage the installation. I guess your (@iffy) options is different, that's why you don't have to manage the installation process. Anyway, my question was about that is there a way/is it possible that the app doesn't uninstall and install (by itself or not, it doesn't matter), but instead, it just apply the patch" on the current installation?

**Comment by iffy** [comment]
@mbtakanov Can you use the `github` provider and configure `host` (inside `package.json`) and `token` in `setFeedURL` as described here: https://github.com/electron-userland/electron-builder/wiki/Publishing-Artifacts#githuboptions--publishconfiguration

**Comment by develar** [comment]
@mbtakanov if you want silent update for boring installer — file issue to electron-builder.

If you want to use private GitHub repo for update — no way (see docs for more details).

**Comment by mbtakanov** [comment]
@iffy I have few questions:
1) I created access token from my company private repo. Then I put it in `token` property. Now my `package.json` look like this:
````
...
"publish": [
      {
        "provider": "github",
        "repo": "repo_name",
        "host": "https://git.companyname.com/repo_name/src/master/foo",
        "protocol": "https",
        "token": "123foobar123foobar"
      }
    ],
...
````
Is this ok?
2) In https://github.com/electron-userland/electron-builder/wiki/Publishing-Artifacts#GithubOptions, the `token` description is somehow incomprehensible. What `Never specify it in the configuration files. Only for setFeedURL.` means? Which files are meant to be `configuration`-able?
3) In https://github.com/electron/electron/blob/master/docs/api/auto-updater.md -> `autoUpdater.setFeedURL(url[, requestHeaders])`
  - what to set as `url`? The URL of the company website (https://git.companyname.com) or the URL to the folder where are the `.exe` and `latest.yml` (https://git.companyname.com/repo_name/src/master/foo) or something else?
  - what to set as `requestHeaders`?

**Comment by develar** [comment]
Docs is clear — https://github.com/electron-userland/electron-builder/wiki/Auto-Update#private-github-update-repo So, in short, do not use private GitHub repo for autoupdate.

**Comment by iffy** [comment]
@mbtakanov I'm closing this (as it seems your use case isn't supported).  But open a new issue or comment on this if you have more questions.

**Comment by nbcnc** [comment]
If @develar is correct -- then the documentation is misleading.  

Please change the docs to indicate that private github repos are **not** supported.  The docs at https://github.com/electron-userland/electron-builder/wiki/Auto-Update#private-github-update-repo say... "You can use a private repository for updates with electron-updater"

**Comment by iffy** [comment]
@nbcnc can you file an issue on that repo?  Or better yet a PR.  I don't control those docs :)

**Comment by nbcnc** [comment]
will do

**Comment by marc-parillo** [comment]
Actually, no need to change the docs.  I looked at the source code and Auto Updater does support private github accounts.  The only way I could get it to work is by calling the 
`autoUpdater.setFeedURL({ provider: 'github', owner: '[repo owner]', repo: '[repo name]',  token: '[gh_token]' })` method before calling `checkForUpdates()` in main.js. 

Of course, doing that is a serious security issue because your private repo token will need to be stored in the source code.   Too bad GitHub doesn't offer read-only repo tokens.

**Comment by develar** [comment]
@marc-parillo Yes, as stated in the docs. https://github.com/electron-userland/electron-builder/wiki/Auto-Update#private-github-update-repo

> Too bad GitHub doesn't offer read-only repo tokens.

Please read solution in the linked issue — https://github.com/electron-userland/electron-builder/issues/1393#issuecomment-288191885

**Comment by marc-parillo** [comment]
@MutableLoss I'm glad you found it helpful.  Fortunately, I was eventually able to host everything in an S3 bucket so I was able to bypass GH altogether.
