### ISSUE TITLE
Fix 'download-progress' example

### ISSUE THREAD

**Issue by dventurino** [iffy/electron-updater-example#16]
Hi,
I think there might be an error in the following lines of the example:
`autoUpdater.on('download-progress', (ev, progressObj) => {
  sendStatusToWindow('Download progress...');
})`

I tried these lines and could not get any info about the download progress...turns out that progressObj is the first argument of the callback function, in fact now I can log the download speed and the other info:
- bytesPerSecond
- percent
- total
- transferred

 Should it be something like this, maybe?
`autoUpdater.on('download-progress', (progressObj) => {
  sendStatusToWindow('Download progress...');
})`

**Comment by iffy** [comment]
Yes, I think it should.  As I understand it, `download-progress` only works on Windows, so I haven't been able to test it :)  If you don't submit a PR, I will a little later.

Thanks!

**Comment by dventurino** [comment]
I sent a PR ;) https://github.com/iffy/electron-updater-example/pull/17

**Comment by iffy** [comment]
@dventurino you rock, thank you!
