### ISSUE TITLE
make autoUpdater.on events have the right signatures (i.e. remove `ev` param)

### ISSUE THREAD

**Issue by honeyjie** [iffy/electron-updater-example#21]
I'm sorry I have one problem when trying to auto-update my app,  I tried the example you leave many times but it can't restart after find a new version and quit , could you help me? I had spent several days on that.

![1](https://user-images.githubusercontent.com/16475074/27023719-5ac68f4a-4f86-11e7-9f3e-c72e4f30aa24.png)

**Comment by honeyjie** [comment]
I made it just now , the version in package.json is old ,it work again when I update , sorry to trouble you

**Comment by honeyjie** [comment]
`autoUpdater.on('download-progress', (ev, progressObj) => {
  sendStatusToWindow('Download progress...');
})  `
should be
`autoUpdater.on('download-progress', (progressObj) => {
  sendStatusToWindow('Download progress...');
})'

**Comment by iffy** [comment]
@honeyjie like this? https://github.com/iffy/electron-updater-example/blob/master/main.js#L82

**Comment by honeyjie** [comment]
yes, but to be sure,  I'll tell you answer tomorrow, the other thing is that  some modules is old version, when I run as the example wrote, it counld not auto-update, unless update the version of 'electron-updater',I am  really appretiate your share that help me a lot, thankyou!

**Comment by iffy** [comment]
@honeyjie what version of `electron-updater` didn't work and which version *did* work?

**Comment by honeyjie** [comment]
electron-updater 2.2.1 can work
and there is no only one argument in the listenning Event, as follows:

![default](https://user-images.githubusercontent.com/16475074/27118834-ba4b55a6-510f-11e7-85d6-a6cbae443c01.PNG)

![default](https://user-images.githubusercontent.com/16475074/27118915-2155cdf8-5110-11e7-8aac-d4bd0d00b73b.PNG)

**Comment by honeyjie** [comment]
hi, I want to disable the default updater style with myown UI , Do you know How to do it? I have spent several hours on that, Could you help?

**Comment by iffy** [comment]
@honeyjie there's no default updater UI with `electron-updater`.  This repo has an example UI, but you can do anything that Electron will let you do.  Is your code public that you could share a link?

As a starting point (from this repo), delete lines 46-100 of this file: https://github.com/iffy/electron-updater-example/blob/master/main.js#L46  And then make your own BrowserWindow loaded with your own HTML file.

**Comment by honeyjie** [comment]
such as the following picture, seems can't be disable or change , I 'm new to electron, and thanks for your answer.
![wechatimg2](https://user-images.githubusercontent.com/16475074/27209892-33495620-5281-11e7-8d5b-13d19fcf9fbf.png)

**Comment by iffy** [comment]
@honeyjie I've never seen that before.  Or that logo...  Can you paste your JavaScript code on Gist or in here?

**Comment by develar** [comment]
This windows — https://github.com/electron-userland/electron-builder/issues/1630

**Comment by iffy** [comment]
Fixed with commit https://github.com/iffy/electron-updater-example/commit/d8c5ddb1efcaabc7ca607fb2c49a9fe9d2e83f97
