### ISSUE TITLE
Complete electron-updater HTTP example connection can not be accessed

### ISSUE THREAD

**Issue by Liupeng8** [iffy/electron-updater-example#24]
Complete electron-updater HTTP example connection can not be accessed

**Comment by iffy** [comment]
What do you mean?  This link is not accessible? https://gist.github.com/iffy/0ff845e8e3f59dbe7eaf2bf24443f104

**Comment by Liupeng8** [comment]
@iffy yes

**Comment by Liupeng8** [comment]
@iffy can you send this demo to my e-mail?   my email address：344312918@qq.com

**Comment by iffy** [comment]
@Liupeng8 k, I emailed it... I'm confused why you can access this page but not the gist...

**Comment by Liupeng8** [comment]
@iffy I am in China, maybe some channels of the network by the operator to intercept it
