### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by pombredanne** [iffy/electron-updater-example#25]
Hi: what would be the license for this fine repo?
 There is some mention of some LHTML team-related LICENSE here but nothing else... https://github.com/iffy/electron-updater-example/blob/d8c5ddb1efcaabc7ca607fb2c49a9fe9d2e83f97/main.js#L1
It might be in reference to https://github.com/iffy/lhtml/blob/master/LICENSE but it would be great to have some clarity wrt this repo, especially if/when use as a base for other stuff.
Thanks!

**Comment by iffy** [comment]
Thanks for that catch -- I started this from another repo.  I'll push an update

**Comment by iffy** [comment]
@pombredanne fixed: https://github.com/iffy/electron-updater-example/blob/master/LICENSE
