### ISSUE TITLE
download v0.4.0  .mac.zip and open the app, show me Error in auto-updater, something wrong?

### ISSUE THREAD

**Issue by xp6530** [iffy/electron-updater-example#30]

**Comment by xp6530** [comment]
![image](https://user-images.githubusercontent.com/18676317/30312111-bab4c89a-97ca-11e7-8292-912e0638710e.png)

**Comment by xp6530** [comment]
sorry, dmg is ok

**Comment by jonwu** [comment]
i keep getting the same error. How did you fix it?
