### ISSUE TITLE
Auto update doesn't work at all

### ISSUE THREAD

**Issue by tangb** [iffy/electron-updater-example#31]
Hi

I tryed this project tuto on my project but it didn't work:
The publish process works well, my files are uploaded to github like expected with new draft release.
But after releasing new version, when I launch previous release bin the update stuff does nothing. So I decided to try with this project directly and I have the same result, updater seems to do nothing.

In my project (not the copy of electron-updater-example) I added logs in all autoUpdater events ('checking-for-update', 'update-available' ...) and I got nothing like autoUpdater was not launched and of course I have no js errors ;)

I read and read again documentation trying to find some clues but I found nothing about my problem.
I'm running my app on linux using appimage file and you can find my test on [my repo](https://github.com/tangb/temp).
Latest electron builder is installed too (electron-builder --version => 19.35.0)
I read a lot of doc about app-update.yml file but I didn't find this file... maybe it's a track
Is it possible you take a look to try to help me ?

Thank you very much :smile:

**Comment by develar** [comment]
I am sorry for confusion – auto updates is not supported on Linux yet.

**Comment by tangb** [comment]
Ok it answer to my problem :grinning: 
Is it planned ?

**Comment by develar** [comment]
Next week :) https://github.com/electron-userland/electron-builder/issues/1138

**Comment by tangb** [comment]
Cool :+1:
Thank you very much :wink:
