### ISSUE TITLE
Github 401 Unauthorized

### ISSUE THREAD

**Issue by btibarra** [iffy/electron-updater-example#36]
Hello, i can't get this example to work, after setting GH_TOKEN on env, when I send npm run publish after packing I get this message:

> Error: Cannot cleanup:
> 
> Error #1 --------------------------------------------------------------------------------
> HttpError: 401 Unauthorized
> {
>   "message": "Bad credentials",
>   "documentation_url": "https://developer.github.com/v3"
> }
> Headers: {
>   "server": "GitHub.com",
>   "date": "Fri, 19 Jan 2018 18:56:04 GMT",
>   "content-type": "application/json; charset=utf-8",
>   "content-length": "83",
>   "connection": "close",
>   "status": "401 Unauthorized",
>   "x-github-media-type": "github.v3; format=json",
>   "x-ratelimit-limit": "60",
>   "x-ratelimit-remaining": "58",
>   "x-ratelimit-reset": "1516390453",
>   "access-control-expose-headers": "ETag, Link, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval",
>   "access-control-allow-origin": "*",
>   "content-security-policy": "default-src 'none'",
>   "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
>   "x-content-type-options": "nosniff",
>   "x-frame-options": "deny",
>   "x-xss-protection": "1; mode=block",
>   "x-runtime-rack": "0.014412",
>   "x-github-request-id": "EA2A:1C8C6:2141FC6:3AA9AC7:5A623F43"
> }
>     at createHttpError (C:\Users\btiba\AppData\Roaming\npm\node_modules\electron-builder\node_modules\builder-util-runtime\src\httpExecutor.ts:31:10)
>     at IncomingMessage.response.on (C:\Users\btiba\AppDat...............
> 
> Error #2 --------------------------------------------------------------------------------
> HttpError: 401 Unauthorized
> {
>   "message": "Bad credentials",
>   "documentation_url": "https://developer.github.com/v3"
> }
> Headers: {
>   "server": "GitHub.com",
>   "date": "Fri, 19 Jan 2018 18:56:04 GMT",
>   "content-type": "application/json; charset=utf-8",
>   "content-length": "83",
>   "connection": "close",
>   "status": "401 Unauthorized",
>   "x-github-media-type": "github.v3; format=json",
>   "x-ratelimit-limit": "60",
>   "x-ratelimit-remaining": "58",
>   "x-ratelimit-reset": "1516390453",
>   "access-control-expose-headers": "ETag, Link, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval",
>   "access-control-allow-origin": "*",
>   "content-security-policy": "default-src 'none'",
>   "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
>   "x-content-type-options": "nosniff",
>   "x-frame-options": "deny",
>   "x-xss-protection": "1; mode=block",
>   "x-runtime-rack": "0.014412",
>   "x-github-request-id": "EA2A:1C8C6:2141FC6:3AA9AC7:5A623F43"
> }
>     at createHttpError (C:\Users\btiba\AppData\Roaming\npm\node_modules\electron-builder\node_modules\builder-util-runtime\src\httpExecuto...............

I need my application to get autoupdates with nsis in windows, i've reading the electron-builder autoupdate documentation but still can't figure out how it really works or the configuration i need to do

**Comment by btibarra** [comment]
It was a problem with my editor, I was running the commands from a terminal there and it wasn't reading correctly the environment variables. It's all working good now :)

**Comment by tytech3** [comment]
I'm getting this issue with a public repo. Did you have a token on your package.json? Not sure why I'd get 401'd on a public project.

**Comment by 3eif** [comment]
> I'm getting this issue with a public repo. Did you have a token on your package.json? Not sure why I'd get 401'd on a public project.

Having the same issue. Did you ever fix it?
