### ISSUE TITLE
I'd love some help

### ISSUE THREAD

**Issue by lieuwe-berg** [iffy/electron-updater-example#42]
I'd love some help, I cannot get it to work.

Here's the index file, there are no errors.
https://github.com/lieuwe-berg/timerapp/blob/master/index.js

I fully understand what the code does but it simply won't update for me. There is nothing else on the screen as well (as in checking for updates).

Everything else works (aka step 2-9).

**Comment by iffy** [comment]
What version of electron-updater, electron-builder, and electron are you using?  Also, what *are* you seeing?

**Comment by lieuwe-berg** [comment]
Thanks for reaching out.

electron: 3.0.2
electron-updater: 3.1.2
electron-builder: 20.28.4

I'm just seeing my regular application. No pop-ups or anything else. This is how I defined my repo:
```json
  "repository": {
		"type": "git",
		"url": "https://github.com/lieuwe-berg/timerapp.git"
  }
``` I see you didn't do that, so how does it recognize it on yours?

**Comment by iffy** [comment]
@lieuwe-berg Have you tried doing the steps in the README exactly?  (Before adding your own code)

The latest versions I've tested with are:

- electron 1.7.9
- electron-updater 2.21.4
- electron-builder 20.8.2

By default, it detects your GitHub settings looking at `.git/config` I think.  

If I get some time, I'll try upgrading the dependencies of this repo to see if there are problems with newer versions (and if that explains what you're seeing)

**Comment by lieuwe-berg** [comment]
That would be awesome, thanks!
I'll try the read.me exactly soon. I just didn't use your code before.

**Comment by iffy** [comment]
@lieuwe-berg I've just tested with the latest versions of things (electron 3.0.2, builder 20.28.4, updater 3.1.2) and it still works on this test repo.  So we can rule that out.

**Comment by lieuwe-berg** [comment]
How do __you__ get it to find you github?

**Comment by iffy** [comment]
@lieuwe-berg by default electron-updater looks at stuff inside the `.git` folder to guess where the GitHub repo is.  For instance, `.git/config` contains details about the `origin` remote.  But you can explicitly set your GitHub repo as described in step 2 here: https://github.com/iffy/electron-updater-example/blob/master/README.md

**Comment by lieuwe-berg** [comment]
Thank you so much! It worked! I can start properly making my app now, thanks again! =D
