### ISSUE TITLE
I could not find releases.atom in github

### ISSUE THREAD

**Issue by finephp** [iffy/electron-updater-example#43]
Hi,iffy ,you did a good job. I forked your electron-updater-example.git ,it's very useful ,and I followed your instructions step by step,every thing is ok,
![image](https://user-images.githubusercontent.com/36813206/49488012-df8e9a80-f87f-11e8-8044-295ccde5fc96.png)

but when I had installed dist/electron-updater-example Setup 0.7.1.exe  and run electron-updater-example.exe ,it's just like this
![image](https://user-images.githubusercontent.com/36813206/49488128-5deb3c80-f880-11e8-874b-305172b93286.png)

undefined url: https://github.com/finephp/electron-updater-example/releases.atom
why? How could I generate this file? Was my GH_TOKEN not correct?But it had published successfly on github releases. Or  is  there something I missed?

 ```
electron-builder version=20.38.2
 packaging       platform=win32 arch=x64 electron=3.0.10 appOutDir=dist\win-unpacked


```
oh,I am very sorry for my Engish,please forgive me for my grammatical mistakes, I hope you can help me solve this problem,thank you very much!

**Comment by DotoPototo** [comment]
@finephp What was your solution? I am getting the exact some error and I am yet to figure out why

**Comment by DotoPototo** [comment]
Okay my reason was because the `releases.atom` link wasn't generating as a private repo so making it public fixed it
