### ISSUE TITLE
'update-downloaded' never gets triggered, even after 'download-progress' is complete

### ISSUE THREAD

**Issue by ionalexandrusecara** [iffy/electron-updater-example#50]
I have followed all the steps [here](https://www.electron.build/auto-update) and pretty much copied the exact same code as [here](https://github.com/iffy/electron-updater-example/blob/master/main.js).

Version:
- electron: ^5.0.7
- electron-updater: ^4.2.4
- electron-builder: ^21.2.0
- electron-notarize: ^0.3.0
- electron-log: ^4.2.2

I use electron-log to log all the steps of the update process. Everything goes perfect, update is detected and downloaded to 100%, under download-progress step. However, update-downloaded never gets triggered, despite the fact that the progress reported under download-progress is 100%. This happens on both Windows 10 and MacOS Catalina 10.15.

![image](https://user-images.githubusercontent.com/15220854/85634802-247c4c80-b631-11ea-8be7-e6d5b39c645e.png)

I tried closing and re-opening the app, but the same thing happens over and over again. Any help would be appreciated.

**Comment by ivangomes** [comment]
did you try:

  "devDependencies": {
    "electron": "^3.0.2",
    "electron-builder": "^22.4.1"
  },
  "dependencies": {
    "electron-log": "^1.3.0",
    "electron-updater": "^4.2.5"
  }

**Comment by ionalexandrusecara** [comment]
@ivangomes I used those and they worked. Is there a particular reason for it?

Also I'm wondering, from your perspective, isn't downgrading all my version very detrimental long term?

**Comment by ionalexandrusecara** [comment]
@ivangomes I've also tried it with the latest electron-log and the latest electron version and it worked as well. This was a really weird one.

**Comment by ivangomes** [comment]
What about electron-builder? Same version?
