### ISSUE TITLE
Example doesn't work with current versions of Electron

### ISSUE THREAD

**Issue by robertpatrick** [iffy/electron-updater-example#53]
This example was very useful in demonstrating the process.  Unfortunately, it uses ancient versions of the dependencies so the code does not work with current versions of Electron (e.g., when creating the BrowserWindow, you now have to enable nodeIntegration or the JavaScript in the HTML file fails to load).  

It also leaves the MacOS signing/notarization as an exercise for the user.  I have a working version of the example for MacOS at https://github.com/robertpatrick/electron-updater-example.

**Comment by ZvikaZ** [comment]
I've also encountered today the issue of the ancient versions, and problems when just updating the versions.

Maybe you could create a PR with your changes (or maybe 2 PRs? One to advance the versions, and one to address the Mac signing issue).

Hopefully they will be integrated soon, and everyone will enjoy your fixes :-)

**Comment by iffy** [comment]
Ancient is accurate :) I'd happily merge a PR which upgrades things.

**Comment by ZvikaZ** [comment]
Hi.
I think https://github.com/iffy/electron-updater-example/pull/54 should address this.
Can it be reviewed?

**Comment by iffy** [comment]
Merged! Thanks all!
