### ISSUE TITLE
Error during update download

### ISSUE THREAD

**Issue by ilgrandeanonimo** [iffy/electron-updater-example#55]
Found version 2.0.0 (url: myapp-2.0.0-arm64-mac.zip, myapp-2.0.0-arm64.dmg)
(node:8559) UnhandledPromiseRejectionWarning: TypeError: Cannot set property 'enabled' of undefined
    at /Users/gattino09/Dev/NodeJS/Electron/myapp/dist/mac-arm64/myapp.app/Contents/Resources/app.asar/main.js:130:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `myapp --trace-warnings ...` to show where the warning was created)
(node:8559) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8559) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by yap241986** [comment]
updater.enabled = true

**Comment by yap241986** [comment]
if I sent to you all my code you can try to fix that problem?
(if you see grammatical error the reason is that I'm Italian)

**Comment by yap241986** [comment]
<img width="296" alt="Schermata 2021-10-20 alle 13 12 07" src="https://user-images.githubusercontent.com/65458792/138082531-e8fdb272-9c80-4f1a-9ca2-3ac251a348c4.png">
how can I hide it?
