### ISSUE TITLE
ERROR using electron-updater with Provider Generic

### ISSUE THREAD

**Issue by EliasG1140** [iffy/electron-updater-example#60]
Hola, no logro entender por que no funciona la actualizacion automatica con un proveedor Generico, donde uso mi propio servidor donde estan colgadas las releases.

El programa abre correctamente, pero no actualiza y en el log tengo lo siguiente..
```
[2023-01-21 16:28:48.611] [info]  Checking for update
[2023-01-21 16:28:48.629] [info]  Generated new staging user ID: 9f802b20-bcb9-5f37-b241-2dd8de4238b9
[2023-01-21 16:28:48.668] [error] Error: Error: net::ERR_SSL_PROTOCOL_ERROR
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49386)
    at SimpleURLLoaderWrapper.emit (node:events:513:28)
```

Ahora bien, la manera en la que esta configurada el electron-builder es la siguiente:
```
  "win": {
    "icon": "resources/icon.ico",
    "publish": [{
      "provider": "generic",
      "url": "http://localhost:3002/version/"
    }],
    "target": [
      {
        "target": "nsis",
        "arch": [
          "x64"
        ]
      }
    ]
  },
```

En la URL `http://localhost:3002/version/` se en cuentran los siguientes archivos:
```
latest.yml
foo-Setup-1.0.1.exe
foo-Setup-1.0.1.exe.blockmap
builder-effective-config.yml
builder-debug.yml
```

No se que estoy haciendo mal, o que deberia hacer para que mi aplicacion pueda tomar las actualizaciones de la URL que le paso, el error que me ahorra de protocolo SSL no se como saltarlo.

**Comment by iffy** [comment]
¿Has leído esta página: https://gist.github.com/iffy/0ff845e8e3f59dbe7eaf2bf24443f104?

¿Tal vez, necessita poner la clave `publish` debajo de `build` en lugar de `win`? No sé.

¿El error "net::ERR_SSL_PROTOCOL_ERROR" es de la actualizacion o de el programa?

**Comment by ivangomes** [comment]
@EliasG1140  Una pregunta, ya hay logrado las actualizaciones con el repo en GitHub?

**Comment by EliasG1140** [comment]
> @EliasG1140  Una pregunta, ya hay logrado las actualizaciones con el repo en GitHub?

Tal ves debería poner un poco más de contexto en la pregunta.

Ya he intentado traer las relases de Github y no hay ningún problema.

El problema es que estoy obligado a usar un propio servidor local, por situaciones geográficas dónde no hay acceso a Internet.

La aplicación en front está con Electrón y React, y el backend en Node con NestJs

**Comment by EliasG1140** [comment]
> ¿Has leído esta página: https://gist.github.com/iffy/0ff845e8e3f59dbe7eaf2bf24443f104?
> 
> ¿Tal vez, necessita poner la clave `publish` debajo de `build` en lugar de `win`? No sé.
> 
> ¿El error "net::ERR_SSL_PROTOCOL_ERROR" es de la actualizacion o de el programa?

Si, de hecho esa fue la guía que encontré para hacerlo inicialmente y no me funcionó.

Colocar la el provider y URL en el `package.json`, cómo también colocarlo en `electron-build.json` o incluso en el archivo `main.ts` de electrón, arroja el mismo error de SSL.

El error SSL lo arroja exactamente el autoUpdate.checkForUpdateAndNotify()

**Comment by EliasG1140** [comment]
Ya pude solucionar, muchas gracias.
Al parecer el error de SSL no pertenecia a 'electorn-updater', y el problema que tenia era que el servidor no estaba proveendo bien los archivos que necesitaba electron para actualizarse.
Supe quer archivos colocarle cuando arregle el Log de autoUpdater, con los log me fue diciendo que estaba pidiendo y a que endpoint estaba consultando.

**Comment by ivangomes** [comment]
Elia cual es tu contacto? Me agrega en instagram @ivangomescombr
